server:
  port: ${EMPLOYEE_PORT:8081}
  shutdown: graceful
  tomcat:
    max-http-form-post-size: 20971520

spring:
  application:
    name: user-service

  config:
    import: optional:configserver:http://localhost:${CONFIG_PORT:8888}

  lifecycle:
    timeout-per-shutdown-phase: 20s

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      leak-detection-threshold: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        

  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USER}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs

  #          issuer-uri: ${KEYCLOAK_ISSUER_URI}

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB

  mvc:
    async:
      request-timeout: 30s

keycloak:
  server-url: ${KEYCLOAK_URL}
  realm: ${KEYCLOAK_REALM}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${CLIENT_SECRET_KEYCLOAK}
  admin-username: ${KEYCLOAK_ADMIN_USER}
  admin-password: ${KEYCLOAK_ADMIN_PWD}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${DISCOVERY_PORT:8761}/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh

  endpoint:
    health:
      show-details: always
    refresh:
      enabled: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: WARN
    org.springframework.security: INFO
    org.springframework.cloud.config: INFO

app:
  bootstrap:
    employee:
      enabled: true
      email: ${EMAIL_ADMIN}
      password: ${BOOTSTRAP_ADMIN_PASSWORD}
      nom: ${NOM_ADMIN}
      prenom: ${PRENOM_ADMIN}