server:
  port: ${GATEWAY_PORT:8080}




spring:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 30MB

  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:${CONFIG_PORT:8888}
  cloud:
    gateway:
      httpclient:
        max-header-size: 16KB
      server:
        webmvc:
          routes:
            - id: user-service-auth
              uri: lb://USER-SERVICE
              predicates:
                - Path=/auth/**

            - id: recrutement-service-cv
              uri: lb://RECRUTEMENT-SERVICE
              predicates:
                - Path=/cv/**

            - id: user-service-users
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users/**,/cessation/**

            - id: user-service-employees
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/employees/**

            - id: user-service-api-users
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/**

            - id: recrutement-service-certifications
              uri: lb://RECRUTEMENT-SERVICE
              predicates:
                - Path=/certifications/**

            - id: user-service-api-admin
              uri: lb://USER-SERVICE
              predicates:
                - Path=/EmployeeManagementController/**

            - id: user-service-ws-admin
              uri: lb://USER-SERVICE
              predicates:
                - Path=/ws-admin/**

            - id: user-service-departements
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/departements/**

            - id: recrutement-service-postes
              uri: lb://RECRUTEMENT-SERVICE
              predicates:
                - Path=/rh/api/postesRecrutement/**

            - id: recrutement-service-candidatures
              uri: lb://RECRUTEMENT-SERVICE
              predicates:
                - Path=/rh/api/candidatures/**

            - id: recrutement-service-candidat
              uri: lb://RECRUTEMENT-SERVICE
              predicates:
                - Path=/candidat/**
            - id: recrutement-service-interviews
              uri: lb://RECRUTEMENT-SERVICE
              predicates:
                - Path=/interviews/**
            - id: recrutement-service-entretiens-cal
              uri: lb://RECRUTEMENT-SERVICE
              predicates:
                - Path=/rh/api/entretiens/**
            - id: recrutement-service-entretiens-candidatt
              uri: lb://RECRUTEMENT-SERVICE
              predicates:
                - Path=/candidat/api/entretiens/**


    loadbalancer:
      cache:
        ttl: 5s
      retry:
        enabled: true
        max-retries-on-same-service-instance: 1
        max-retries-on-next-service-instance: 2
        retry-on-all-operations: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:${DISCOVERY_PORT:8761}/eureka/
    registry-fetch-interval-seconds: 5

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway