package service.recrutement.WebSocket;

public enum RecrutementEventType {
    NEW_POSTE,
    POSTE_STATUS_CHANGED,
    NEW_APPLICATION,
    APPLICATION_STATUS_CHANGED,
    INTERVIEW_PLANIFIE,
    INTERVIEW_REPORTE,
    INTERVIEW_ANNULE,
    INTERVIEW_ABSENT,
    INTERVIEW_RESULTAT,
    REPROGRAMMATION_DEMANDEE,
    REPROGRAMMATION_TRAITEE
}