pipeline {
    agent any

    environment {
        IMAGE_NAME = "stage-discovery"
        IMAGE_TAG  = "${env.BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'dev',
                    credentialsId: 'git_ssh',
                    url: 'https://github.com/zayedhamadi/microservice_intern.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('discovery') {
                    script {
                        docker.build("${IMAGE_NAME}:${IMAGE_TAG}")
                    }
                }
            }
        }
    }

    post {
        success { echo "Build réussi pour discovery #${env.BUILD_NUMBER}" }
        failure { echo "Échec du pipeline discovery #${env.BUILD_NUMBER}" }
    }
}